### PR TITLE
xlight codebase - traffic lights for a smart city

### PR DESCRIPTION
**Pull request by BastiTee**
Consists...

- city-server : Simulation of a traffic control system handling traffic light states written in Python/Django
- client : Native android application receiving beacon payload and reading from traffic control system
- Ampel.ino : Text file containing arduino compatible traffic light binaries written in C
- some docu

### CODE REVIEW

**Comment by carlj** [comment]
could you please move the result in a new "result" folder? That would be perfect.

**Comment by BastiTee** [comment]
What do mean? Currently our code project is below `<REPO>/smartampel`
And you want it to be in `<REPO>/result` ?

**Comment by carlj** [comment]
Yes, just move the code to the subfolder results:
<REPO>/results/smartampel

Thx


> Am 22.09.2017 um 14:58 schrieb Basti Tee <notifications@github.com>:
> 
> smartampel

**Comment by BastiTee** [comment]
Ok done.
Thanks.

**Comment by carlj** [comment]
done and closed. I also added all of you to the list of contributors.

**Pull request merged**
